//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSModule.Webservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLoginDetails", ReplyAction="http://tempuri.org/IService1/GetLoginDetailsResponse")]
        bool GetLoginDetails(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetLoginDetails", ReplyAction="http://tempuri.org/IService1/GetLoginDetailsResponse")]
        System.IAsyncResult BeginGetLoginDetails(string username, string password, System.AsyncCallback callback, object asyncState);
        
        bool EndGetLoginDetails(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SMSModule.Webservice.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLoginDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLoginDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SMSModule.Webservice.IService1>, SMSModule.Webservice.IService1 {
        
        private BeginOperationDelegate onBeginGetLoginDetailsDelegate;
        
        private EndOperationDelegate onEndGetLoginDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onGetLoginDetailsCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetLoginDetailsCompletedEventArgs> GetLoginDetailsCompleted;
        
        public bool GetLoginDetails(string username, string password) {
            return base.Channel.GetLoginDetails(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetLoginDetails(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLoginDetails(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndGetLoginDetails(System.IAsyncResult result) {
            return base.Channel.EndGetLoginDetails(result);
        }
        
        private System.IAsyncResult OnBeginGetLoginDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginGetLoginDetails(username, password, callback, asyncState);
        }
        
        private object[] OnEndGetLoginDetails(System.IAsyncResult result) {
            bool retVal = this.EndGetLoginDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLoginDetailsCompleted(object state) {
            if ((this.GetLoginDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLoginDetailsCompleted(this, new GetLoginDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLoginDetailsAsync(string username, string password) {
            this.GetLoginDetailsAsync(username, password, null);
        }
        
        public void GetLoginDetailsAsync(string username, string password, object userState) {
            if ((this.onBeginGetLoginDetailsDelegate == null)) {
                this.onBeginGetLoginDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetLoginDetails);
            }
            if ((this.onEndGetLoginDetailsDelegate == null)) {
                this.onEndGetLoginDetailsDelegate = new EndOperationDelegate(this.OnEndGetLoginDetails);
            }
            if ((this.onGetLoginDetailsCompletedDelegate == null)) {
                this.onGetLoginDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLoginDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetLoginDetailsDelegate, new object[] {
                        username,
                        password}, this.onEndGetLoginDetailsDelegate, this.onGetLoginDetailsCompletedDelegate, userState);
        }
    }
}
