//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSModule.Webservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Announcement", Namespace="http://schemas.datacontract.org/2004/07/Webservice")]
    [System.SerializableAttribute()]
    public partial class Announcement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassID {
            get {
                return this.ClassIDField;
            }
            set {
                if ((this.ClassIDField.Equals(value) != true)) {
                    this.ClassIDField = value;
                    this.RaisePropertyChanged("ClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((this.CreatorField.Equals(value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Webservice.DB")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSModule.Webservice.Parent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSModule.Webservice.Student))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSModule.Webservice.Teacher))]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkschoolidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastloginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhonenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserroleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdateField, value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fkschoolid {
            get {
                return this.FkschoolidField;
            }
            set {
                if ((this.FkschoolidField.Equals(value) != true)) {
                    this.FkschoolidField = value;
                    this.RaisePropertyChanged("Fkschoolid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Lastlogin {
            get {
                return this.LastloginField;
            }
            set {
                if ((this.LastloginField.Equals(value) != true)) {
                    this.LastloginField = value;
                    this.RaisePropertyChanged("Lastlogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Phonenumber {
            get {
                return this.PhonenumberField;
            }
            set {
                if ((this.PhonenumberField.Equals(value) != true)) {
                    this.PhonenumberField = value;
                    this.RaisePropertyChanged("Phonenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Userrole {
            get {
                return this.UserroleField;
            }
            set {
                if ((this.UserroleField.Equals(value) != true)) {
                    this.UserroleField = value;
                    this.RaisePropertyChanged("Userrole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parent", Namespace="http://schemas.datacontract.org/2004/07/Webservice.DB")]
    [System.SerializableAttribute()]
    public partial class Parent : SMSModule.Webservice.User {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkuseridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fkuserid {
            get {
                return this.FkuseridField;
            }
            set {
                if ((this.FkuseridField.Equals(value) != true)) {
                    this.FkuseridField = value;
                    this.RaisePropertyChanged("Fkuserid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/Webservice.DB")]
    [System.SerializableAttribute()]
    public partial class Student : SMSModule.Webservice.User {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkClassidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkuseridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FkClassid {
            get {
                return this.FkClassidField;
            }
            set {
                if ((this.FkClassidField.Equals(value) != true)) {
                    this.FkClassidField = value;
                    this.RaisePropertyChanged("FkClassid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fkuserid {
            get {
                return this.FkuseridField;
            }
            set {
                if ((this.FkuseridField.Equals(value) != true)) {
                    this.FkuseridField = value;
                    this.RaisePropertyChanged("Fkuserid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/Webservice.DB")]
    [System.SerializableAttribute()]
    public partial class Teacher : SMSModule.Webservice.User {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkuseridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fkuserid {
            get {
                return this.FkuseridField;
            }
            set {
                if ((this.FkuseridField.Equals(value) != true)) {
                    this.FkuseridField = value;
                    this.RaisePropertyChanged("Fkuserid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class", Namespace="http://schemas.datacontract.org/2004/07/Webservice.DB")]
    [System.SerializableAttribute()]
    public partial class Class : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkschoolidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FkteacheridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fkschoolid {
            get {
                return this.FkschoolidField;
            }
            set {
                if ((this.FkschoolidField.Equals(value) != true)) {
                    this.FkschoolidField = value;
                    this.RaisePropertyChanged("Fkschoolid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fkteacherid {
            get {
                return this.FkteacheridField;
            }
            set {
                if ((this.FkteacheridField.Equals(value) != true)) {
                    this.FkteacheridField = value;
                    this.RaisePropertyChanged("Fkteacherid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservice.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLoginDetails", ReplyAction="http://tempuri.org/IService1/GetLoginDetailsResponse")]
        bool GetLoginDetails(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetLoginDetails", ReplyAction="http://tempuri.org/IService1/GetLoginDetailsResponse")]
        System.IAsyncResult BeginGetLoginDetails(string username, string password, System.AsyncCallback callback, object asyncState);
        
        bool EndGetLoginDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserDetails", ReplyAction="http://tempuri.org/IService1/GetUserDetailsResponse")]
        string GetUserDetails(int number);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetUserDetails", ReplyAction="http://tempuri.org/IService1/GetUserDetailsResponse")]
        System.IAsyncResult BeginGetUserDetails(int number, System.AsyncCallback callback, object asyncState);
        
        string EndGetUserDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAnnouncement", ReplyAction="http://tempuri.org/IService1/CreateAnnouncementResponse")]
        bool CreateAnnouncement(int creator, string header, string message, int group, int classID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/CreateAnnouncement", ReplyAction="http://tempuri.org/IService1/CreateAnnouncementResponse")]
        System.IAsyncResult BeginCreateAnnouncement(int creator, string header, string message, int group, int classID, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateAnnouncement(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAnnouncements", ReplyAction="http://tempuri.org/IService1/GetAnnouncementsResponse")]
        System.Collections.Generic.List<SMSModule.Webservice.Announcement> GetAnnouncements(int group, int classID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAnnouncements", ReplyAction="http://tempuri.org/IService1/GetAnnouncementsResponse")]
        System.IAsyncResult BeginGetAnnouncements(int group, int classID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<SMSModule.Webservice.Announcement> EndGetAnnouncements(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        bool ChangePassword(int id, string oldPass, string newPass, string confirmPass);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ChangePassword", ReplyAction="http://tempuri.org/IService1/ChangePasswordResponse")]
        System.IAsyncResult BeginChangePassword(int id, string oldPass, string newPass, string confirmPass, System.AsyncCallback callback, object asyncState);
        
        bool EndChangePassword(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertTeacher", ReplyAction="http://tempuri.org/IService1/InsertTeacherResponse")]
        bool InsertTeacher(SMSModule.Webservice.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/InsertTeacher", ReplyAction="http://tempuri.org/IService1/InsertTeacherResponse")]
        System.IAsyncResult BeginInsertTeacher(SMSModule.Webservice.Teacher teacher, System.AsyncCallback callback, object asyncState);
        
        bool EndInsertTeacher(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeachers", ReplyAction="http://tempuri.org/IService1/GetTeachersResponse")]
        System.Collections.Generic.List<SMSModule.Webservice.Teacher> GetTeachers();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetTeachers", ReplyAction="http://tempuri.org/IService1/GetTeachersResponse")]
        System.IAsyncResult BeginGetTeachers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<SMSModule.Webservice.Teacher> EndGetTeachers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertParent", ReplyAction="http://tempuri.org/IService1/InsertParentResponse")]
        bool InsertParent(SMSModule.Webservice.Parent parent);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/InsertParent", ReplyAction="http://tempuri.org/IService1/InsertParentResponse")]
        System.IAsyncResult BeginInsertParent(SMSModule.Webservice.Parent parent, System.AsyncCallback callback, object asyncState);
        
        bool EndInsertParent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetParents", ReplyAction="http://tempuri.org/IService1/GetParentsResponse")]
        System.Collections.Generic.List<SMSModule.Webservice.Parent> GetParents();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetParents", ReplyAction="http://tempuri.org/IService1/GetParentsResponse")]
        System.IAsyncResult BeginGetParents(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<SMSModule.Webservice.Parent> EndGetParents(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStudent", ReplyAction="http://tempuri.org/IService1/InsertStudentResponse")]
        bool InsertStudent(SMSModule.Webservice.Student parent);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/InsertStudent", ReplyAction="http://tempuri.org/IService1/InsertStudentResponse")]
        System.IAsyncResult BeginInsertStudent(SMSModule.Webservice.Student parent, System.AsyncCallback callback, object asyncState);
        
        bool EndInsertStudent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudents", ReplyAction="http://tempuri.org/IService1/GetStudentsResponse")]
        System.Collections.Generic.List<SMSModule.Webservice.Student> GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetStudents", ReplyAction="http://tempuri.org/IService1/GetStudentsResponse")]
        System.IAsyncResult BeginGetStudents(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<SMSModule.Webservice.Student> EndGetStudents(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClasses", ReplyAction="http://tempuri.org/IService1/GetClassesResponse")]
        System.Collections.Generic.List<SMSModule.Webservice.Class> GetClasses();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetClasses", ReplyAction="http://tempuri.org/IService1/GetClassesResponse")]
        System.IAsyncResult BeginGetClasses(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<SMSModule.Webservice.Class> EndGetClasses(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertClass", ReplyAction="http://tempuri.org/IService1/InsertClassResponse")]
        bool InsertClass(SMSModule.Webservice.Class theClass);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/InsertClass", ReplyAction="http://tempuri.org/IService1/InsertClassResponse")]
        System.IAsyncResult BeginInsertClass(SMSModule.Webservice.Class theClass, System.AsyncCallback callback, object asyncState);
        
        bool EndInsertClass(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SMSModule.Webservice.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLoginDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLoginDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateAnnouncementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateAnnouncementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAnnouncementsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAnnouncementsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Announcement> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<SMSModule.Webservice.Announcement>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertTeacherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertTeacherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTeachersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTeachersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Teacher> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<SMSModule.Webservice.Teacher>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertParentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertParentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetParentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetParentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Parent> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<SMSModule.Webservice.Parent>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Student> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<SMSModule.Webservice.Student>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClassesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClassesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Class> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<SMSModule.Webservice.Class>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SMSModule.Webservice.IService1>, SMSModule.Webservice.IService1 {
        
        private BeginOperationDelegate onBeginGetLoginDetailsDelegate;
        
        private EndOperationDelegate onEndGetLoginDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onGetLoginDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserDetailsDelegate;
        
        private EndOperationDelegate onEndGetUserDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateAnnouncementDelegate;
        
        private EndOperationDelegate onEndCreateAnnouncementDelegate;
        
        private System.Threading.SendOrPostCallback onCreateAnnouncementCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAnnouncementsDelegate;
        
        private EndOperationDelegate onEndGetAnnouncementsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAnnouncementsCompletedDelegate;
        
        private BeginOperationDelegate onBeginChangePasswordDelegate;
        
        private EndOperationDelegate onEndChangePasswordDelegate;
        
        private System.Threading.SendOrPostCallback onChangePasswordCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertTeacherDelegate;
        
        private EndOperationDelegate onEndInsertTeacherDelegate;
        
        private System.Threading.SendOrPostCallback onInsertTeacherCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTeachersDelegate;
        
        private EndOperationDelegate onEndGetTeachersDelegate;
        
        private System.Threading.SendOrPostCallback onGetTeachersCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertParentDelegate;
        
        private EndOperationDelegate onEndInsertParentDelegate;
        
        private System.Threading.SendOrPostCallback onInsertParentCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetParentsDelegate;
        
        private EndOperationDelegate onEndGetParentsDelegate;
        
        private System.Threading.SendOrPostCallback onGetParentsCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertStudentDelegate;
        
        private EndOperationDelegate onEndInsertStudentDelegate;
        
        private System.Threading.SendOrPostCallback onInsertStudentCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStudentsDelegate;
        
        private EndOperationDelegate onEndGetStudentsDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetClassesDelegate;
        
        private EndOperationDelegate onEndGetClassesDelegate;
        
        private System.Threading.SendOrPostCallback onGetClassesCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertClassDelegate;
        
        private EndOperationDelegate onEndInsertClassDelegate;
        
        private System.Threading.SendOrPostCallback onInsertClassCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetLoginDetailsCompletedEventArgs> GetLoginDetailsCompleted;
        
        public event System.EventHandler<GetUserDetailsCompletedEventArgs> GetUserDetailsCompleted;
        
        public event System.EventHandler<CreateAnnouncementCompletedEventArgs> CreateAnnouncementCompleted;
        
        public event System.EventHandler<GetAnnouncementsCompletedEventArgs> GetAnnouncementsCompleted;
        
        public event System.EventHandler<ChangePasswordCompletedEventArgs> ChangePasswordCompleted;
        
        public event System.EventHandler<InsertTeacherCompletedEventArgs> InsertTeacherCompleted;
        
        public event System.EventHandler<GetTeachersCompletedEventArgs> GetTeachersCompleted;
        
        public event System.EventHandler<InsertParentCompletedEventArgs> InsertParentCompleted;
        
        public event System.EventHandler<GetParentsCompletedEventArgs> GetParentsCompleted;
        
        public event System.EventHandler<InsertStudentCompletedEventArgs> InsertStudentCompleted;
        
        public event System.EventHandler<GetStudentsCompletedEventArgs> GetStudentsCompleted;
        
        public event System.EventHandler<GetClassesCompletedEventArgs> GetClassesCompleted;
        
        public event System.EventHandler<InsertClassCompletedEventArgs> InsertClassCompleted;
        
        public bool GetLoginDetails(string username, string password) {
            return base.Channel.GetLoginDetails(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetLoginDetails(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLoginDetails(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndGetLoginDetails(System.IAsyncResult result) {
            return base.Channel.EndGetLoginDetails(result);
        }
        
        private System.IAsyncResult OnBeginGetLoginDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginGetLoginDetails(username, password, callback, asyncState);
        }
        
        private object[] OnEndGetLoginDetails(System.IAsyncResult result) {
            bool retVal = this.EndGetLoginDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLoginDetailsCompleted(object state) {
            if ((this.GetLoginDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLoginDetailsCompleted(this, new GetLoginDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLoginDetailsAsync(string username, string password) {
            this.GetLoginDetailsAsync(username, password, null);
        }
        
        public void GetLoginDetailsAsync(string username, string password, object userState) {
            if ((this.onBeginGetLoginDetailsDelegate == null)) {
                this.onBeginGetLoginDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetLoginDetails);
            }
            if ((this.onEndGetLoginDetailsDelegate == null)) {
                this.onEndGetLoginDetailsDelegate = new EndOperationDelegate(this.OnEndGetLoginDetails);
            }
            if ((this.onGetLoginDetailsCompletedDelegate == null)) {
                this.onGetLoginDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLoginDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetLoginDetailsDelegate, new object[] {
                        username,
                        password}, this.onEndGetLoginDetailsDelegate, this.onGetLoginDetailsCompletedDelegate, userState);
        }
        
        public string GetUserDetails(int number) {
            return base.Channel.GetUserDetails(number);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUserDetails(int number, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserDetails(number, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetUserDetails(System.IAsyncResult result) {
            return base.Channel.EndGetUserDetails(result);
        }
        
        private System.IAsyncResult OnBeginGetUserDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int number = ((int)(inValues[0]));
            return this.BeginGetUserDetails(number, callback, asyncState);
        }
        
        private object[] OnEndGetUserDetails(System.IAsyncResult result) {
            string retVal = this.EndGetUserDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserDetailsCompleted(object state) {
            if ((this.GetUserDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserDetailsCompleted(this, new GetUserDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserDetailsAsync(int number) {
            this.GetUserDetailsAsync(number, null);
        }
        
        public void GetUserDetailsAsync(int number, object userState) {
            if ((this.onBeginGetUserDetailsDelegate == null)) {
                this.onBeginGetUserDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetUserDetails);
            }
            if ((this.onEndGetUserDetailsDelegate == null)) {
                this.onEndGetUserDetailsDelegate = new EndOperationDelegate(this.OnEndGetUserDetails);
            }
            if ((this.onGetUserDetailsCompletedDelegate == null)) {
                this.onGetUserDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserDetailsDelegate, new object[] {
                        number}, this.onEndGetUserDetailsDelegate, this.onGetUserDetailsCompletedDelegate, userState);
        }
        
        public bool CreateAnnouncement(int creator, string header, string message, int group, int classID) {
            return base.Channel.CreateAnnouncement(creator, header, message, group, classID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreateAnnouncement(int creator, string header, string message, int group, int classID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateAnnouncement(creator, header, message, group, classID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndCreateAnnouncement(System.IAsyncResult result) {
            return base.Channel.EndCreateAnnouncement(result);
        }
        
        private System.IAsyncResult OnBeginCreateAnnouncement(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int creator = ((int)(inValues[0]));
            string header = ((string)(inValues[1]));
            string message = ((string)(inValues[2]));
            int group = ((int)(inValues[3]));
            int classID = ((int)(inValues[4]));
            return this.BeginCreateAnnouncement(creator, header, message, group, classID, callback, asyncState);
        }
        
        private object[] OnEndCreateAnnouncement(System.IAsyncResult result) {
            bool retVal = this.EndCreateAnnouncement(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateAnnouncementCompleted(object state) {
            if ((this.CreateAnnouncementCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateAnnouncementCompleted(this, new CreateAnnouncementCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateAnnouncementAsync(int creator, string header, string message, int group, int classID) {
            this.CreateAnnouncementAsync(creator, header, message, group, classID, null);
        }
        
        public void CreateAnnouncementAsync(int creator, string header, string message, int group, int classID, object userState) {
            if ((this.onBeginCreateAnnouncementDelegate == null)) {
                this.onBeginCreateAnnouncementDelegate = new BeginOperationDelegate(this.OnBeginCreateAnnouncement);
            }
            if ((this.onEndCreateAnnouncementDelegate == null)) {
                this.onEndCreateAnnouncementDelegate = new EndOperationDelegate(this.OnEndCreateAnnouncement);
            }
            if ((this.onCreateAnnouncementCompletedDelegate == null)) {
                this.onCreateAnnouncementCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateAnnouncementCompleted);
            }
            base.InvokeAsync(this.onBeginCreateAnnouncementDelegate, new object[] {
                        creator,
                        header,
                        message,
                        group,
                        classID}, this.onEndCreateAnnouncementDelegate, this.onCreateAnnouncementCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Announcement> GetAnnouncements(int group, int classID) {
            return base.Channel.GetAnnouncements(group, classID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAnnouncements(int group, int classID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAnnouncements(group, classID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<SMSModule.Webservice.Announcement> EndGetAnnouncements(System.IAsyncResult result) {
            return base.Channel.EndGetAnnouncements(result);
        }
        
        private System.IAsyncResult OnBeginGetAnnouncements(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int group = ((int)(inValues[0]));
            int classID = ((int)(inValues[1]));
            return this.BeginGetAnnouncements(group, classID, callback, asyncState);
        }
        
        private object[] OnEndGetAnnouncements(System.IAsyncResult result) {
            System.Collections.Generic.List<SMSModule.Webservice.Announcement> retVal = this.EndGetAnnouncements(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAnnouncementsCompleted(object state) {
            if ((this.GetAnnouncementsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAnnouncementsCompleted(this, new GetAnnouncementsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAnnouncementsAsync(int group, int classID) {
            this.GetAnnouncementsAsync(group, classID, null);
        }
        
        public void GetAnnouncementsAsync(int group, int classID, object userState) {
            if ((this.onBeginGetAnnouncementsDelegate == null)) {
                this.onBeginGetAnnouncementsDelegate = new BeginOperationDelegate(this.OnBeginGetAnnouncements);
            }
            if ((this.onEndGetAnnouncementsDelegate == null)) {
                this.onEndGetAnnouncementsDelegate = new EndOperationDelegate(this.OnEndGetAnnouncements);
            }
            if ((this.onGetAnnouncementsCompletedDelegate == null)) {
                this.onGetAnnouncementsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAnnouncementsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAnnouncementsDelegate, new object[] {
                        group,
                        classID}, this.onEndGetAnnouncementsDelegate, this.onGetAnnouncementsCompletedDelegate, userState);
        }
        
        public bool ChangePassword(int id, string oldPass, string newPass, string confirmPass) {
            return base.Channel.ChangePassword(id, oldPass, newPass, confirmPass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginChangePassword(int id, string oldPass, string newPass, string confirmPass, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangePassword(id, oldPass, newPass, confirmPass, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndChangePassword(System.IAsyncResult result) {
            return base.Channel.EndChangePassword(result);
        }
        
        private System.IAsyncResult OnBeginChangePassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            string oldPass = ((string)(inValues[1]));
            string newPass = ((string)(inValues[2]));
            string confirmPass = ((string)(inValues[3]));
            return this.BeginChangePassword(id, oldPass, newPass, confirmPass, callback, asyncState);
        }
        
        private object[] OnEndChangePassword(System.IAsyncResult result) {
            bool retVal = this.EndChangePassword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChangePasswordCompleted(object state) {
            if ((this.ChangePasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangePasswordAsync(int id, string oldPass, string newPass, string confirmPass) {
            this.ChangePasswordAsync(id, oldPass, newPass, confirmPass, null);
        }
        
        public void ChangePasswordAsync(int id, string oldPass, string newPass, string confirmPass, object userState) {
            if ((this.onBeginChangePasswordDelegate == null)) {
                this.onBeginChangePasswordDelegate = new BeginOperationDelegate(this.OnBeginChangePassword);
            }
            if ((this.onEndChangePasswordDelegate == null)) {
                this.onEndChangePasswordDelegate = new EndOperationDelegate(this.OnEndChangePassword);
            }
            if ((this.onChangePasswordCompletedDelegate == null)) {
                this.onChangePasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangePasswordCompleted);
            }
            base.InvokeAsync(this.onBeginChangePasswordDelegate, new object[] {
                        id,
                        oldPass,
                        newPass,
                        confirmPass}, this.onEndChangePasswordDelegate, this.onChangePasswordCompletedDelegate, userState);
        }
        
        public bool InsertTeacher(SMSModule.Webservice.Teacher teacher) {
            return base.Channel.InsertTeacher(teacher);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInsertTeacher(SMSModule.Webservice.Teacher teacher, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertTeacher(teacher, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndInsertTeacher(System.IAsyncResult result) {
            return base.Channel.EndInsertTeacher(result);
        }
        
        private System.IAsyncResult OnBeginInsertTeacher(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SMSModule.Webservice.Teacher teacher = ((SMSModule.Webservice.Teacher)(inValues[0]));
            return this.BeginInsertTeacher(teacher, callback, asyncState);
        }
        
        private object[] OnEndInsertTeacher(System.IAsyncResult result) {
            bool retVal = this.EndInsertTeacher(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertTeacherCompleted(object state) {
            if ((this.InsertTeacherCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertTeacherCompleted(this, new InsertTeacherCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertTeacherAsync(SMSModule.Webservice.Teacher teacher) {
            this.InsertTeacherAsync(teacher, null);
        }
        
        public void InsertTeacherAsync(SMSModule.Webservice.Teacher teacher, object userState) {
            if ((this.onBeginInsertTeacherDelegate == null)) {
                this.onBeginInsertTeacherDelegate = new BeginOperationDelegate(this.OnBeginInsertTeacher);
            }
            if ((this.onEndInsertTeacherDelegate == null)) {
                this.onEndInsertTeacherDelegate = new EndOperationDelegate(this.OnEndInsertTeacher);
            }
            if ((this.onInsertTeacherCompletedDelegate == null)) {
                this.onInsertTeacherCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertTeacherCompleted);
            }
            base.InvokeAsync(this.onBeginInsertTeacherDelegate, new object[] {
                        teacher}, this.onEndInsertTeacherDelegate, this.onInsertTeacherCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Teacher> GetTeachers() {
            return base.Channel.GetTeachers();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetTeachers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTeachers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<SMSModule.Webservice.Teacher> EndGetTeachers(System.IAsyncResult result) {
            return base.Channel.EndGetTeachers(result);
        }
        
        private System.IAsyncResult OnBeginGetTeachers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetTeachers(callback, asyncState);
        }
        
        private object[] OnEndGetTeachers(System.IAsyncResult result) {
            System.Collections.Generic.List<SMSModule.Webservice.Teacher> retVal = this.EndGetTeachers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTeachersCompleted(object state) {
            if ((this.GetTeachersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTeachersCompleted(this, new GetTeachersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTeachersAsync() {
            this.GetTeachersAsync(null);
        }
        
        public void GetTeachersAsync(object userState) {
            if ((this.onBeginGetTeachersDelegate == null)) {
                this.onBeginGetTeachersDelegate = new BeginOperationDelegate(this.OnBeginGetTeachers);
            }
            if ((this.onEndGetTeachersDelegate == null)) {
                this.onEndGetTeachersDelegate = new EndOperationDelegate(this.OnEndGetTeachers);
            }
            if ((this.onGetTeachersCompletedDelegate == null)) {
                this.onGetTeachersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTeachersCompleted);
            }
            base.InvokeAsync(this.onBeginGetTeachersDelegate, null, this.onEndGetTeachersDelegate, this.onGetTeachersCompletedDelegate, userState);
        }
        
        public bool InsertParent(SMSModule.Webservice.Parent parent) {
            return base.Channel.InsertParent(parent);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInsertParent(SMSModule.Webservice.Parent parent, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertParent(parent, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndInsertParent(System.IAsyncResult result) {
            return base.Channel.EndInsertParent(result);
        }
        
        private System.IAsyncResult OnBeginInsertParent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SMSModule.Webservice.Parent parent = ((SMSModule.Webservice.Parent)(inValues[0]));
            return this.BeginInsertParent(parent, callback, asyncState);
        }
        
        private object[] OnEndInsertParent(System.IAsyncResult result) {
            bool retVal = this.EndInsertParent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertParentCompleted(object state) {
            if ((this.InsertParentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertParentCompleted(this, new InsertParentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertParentAsync(SMSModule.Webservice.Parent parent) {
            this.InsertParentAsync(parent, null);
        }
        
        public void InsertParentAsync(SMSModule.Webservice.Parent parent, object userState) {
            if ((this.onBeginInsertParentDelegate == null)) {
                this.onBeginInsertParentDelegate = new BeginOperationDelegate(this.OnBeginInsertParent);
            }
            if ((this.onEndInsertParentDelegate == null)) {
                this.onEndInsertParentDelegate = new EndOperationDelegate(this.OnEndInsertParent);
            }
            if ((this.onInsertParentCompletedDelegate == null)) {
                this.onInsertParentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertParentCompleted);
            }
            base.InvokeAsync(this.onBeginInsertParentDelegate, new object[] {
                        parent}, this.onEndInsertParentDelegate, this.onInsertParentCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Parent> GetParents() {
            return base.Channel.GetParents();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetParents(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetParents(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<SMSModule.Webservice.Parent> EndGetParents(System.IAsyncResult result) {
            return base.Channel.EndGetParents(result);
        }
        
        private System.IAsyncResult OnBeginGetParents(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetParents(callback, asyncState);
        }
        
        private object[] OnEndGetParents(System.IAsyncResult result) {
            System.Collections.Generic.List<SMSModule.Webservice.Parent> retVal = this.EndGetParents(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetParentsCompleted(object state) {
            if ((this.GetParentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetParentsCompleted(this, new GetParentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetParentsAsync() {
            this.GetParentsAsync(null);
        }
        
        public void GetParentsAsync(object userState) {
            if ((this.onBeginGetParentsDelegate == null)) {
                this.onBeginGetParentsDelegate = new BeginOperationDelegate(this.OnBeginGetParents);
            }
            if ((this.onEndGetParentsDelegate == null)) {
                this.onEndGetParentsDelegate = new EndOperationDelegate(this.OnEndGetParents);
            }
            if ((this.onGetParentsCompletedDelegate == null)) {
                this.onGetParentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetParentsCompleted);
            }
            base.InvokeAsync(this.onBeginGetParentsDelegate, null, this.onEndGetParentsDelegate, this.onGetParentsCompletedDelegate, userState);
        }
        
        public bool InsertStudent(SMSModule.Webservice.Student parent) {
            return base.Channel.InsertStudent(parent);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInsertStudent(SMSModule.Webservice.Student parent, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertStudent(parent, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndInsertStudent(System.IAsyncResult result) {
            return base.Channel.EndInsertStudent(result);
        }
        
        private System.IAsyncResult OnBeginInsertStudent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SMSModule.Webservice.Student parent = ((SMSModule.Webservice.Student)(inValues[0]));
            return this.BeginInsertStudent(parent, callback, asyncState);
        }
        
        private object[] OnEndInsertStudent(System.IAsyncResult result) {
            bool retVal = this.EndInsertStudent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertStudentCompleted(object state) {
            if ((this.InsertStudentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertStudentCompleted(this, new InsertStudentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertStudentAsync(SMSModule.Webservice.Student parent) {
            this.InsertStudentAsync(parent, null);
        }
        
        public void InsertStudentAsync(SMSModule.Webservice.Student parent, object userState) {
            if ((this.onBeginInsertStudentDelegate == null)) {
                this.onBeginInsertStudentDelegate = new BeginOperationDelegate(this.OnBeginInsertStudent);
            }
            if ((this.onEndInsertStudentDelegate == null)) {
                this.onEndInsertStudentDelegate = new EndOperationDelegate(this.OnEndInsertStudent);
            }
            if ((this.onInsertStudentCompletedDelegate == null)) {
                this.onInsertStudentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertStudentCompleted);
            }
            base.InvokeAsync(this.onBeginInsertStudentDelegate, new object[] {
                        parent}, this.onEndInsertStudentDelegate, this.onInsertStudentCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Student> GetStudents() {
            return base.Channel.GetStudents();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetStudents(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudents(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<SMSModule.Webservice.Student> EndGetStudents(System.IAsyncResult result) {
            return base.Channel.EndGetStudents(result);
        }
        
        private System.IAsyncResult OnBeginGetStudents(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetStudents(callback, asyncState);
        }
        
        private object[] OnEndGetStudents(System.IAsyncResult result) {
            System.Collections.Generic.List<SMSModule.Webservice.Student> retVal = this.EndGetStudents(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentsCompleted(object state) {
            if ((this.GetStudentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentsCompleted(this, new GetStudentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentsAsync() {
            this.GetStudentsAsync(null);
        }
        
        public void GetStudentsAsync(object userState) {
            if ((this.onBeginGetStudentsDelegate == null)) {
                this.onBeginGetStudentsDelegate = new BeginOperationDelegate(this.OnBeginGetStudents);
            }
            if ((this.onEndGetStudentsDelegate == null)) {
                this.onEndGetStudentsDelegate = new EndOperationDelegate(this.OnEndGetStudents);
            }
            if ((this.onGetStudentsCompletedDelegate == null)) {
                this.onGetStudentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentsCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentsDelegate, null, this.onEndGetStudentsDelegate, this.onGetStudentsCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<SMSModule.Webservice.Class> GetClasses() {
            return base.Channel.GetClasses();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetClasses(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClasses(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<SMSModule.Webservice.Class> EndGetClasses(System.IAsyncResult result) {
            return base.Channel.EndGetClasses(result);
        }
        
        private System.IAsyncResult OnBeginGetClasses(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetClasses(callback, asyncState);
        }
        
        private object[] OnEndGetClasses(System.IAsyncResult result) {
            System.Collections.Generic.List<SMSModule.Webservice.Class> retVal = this.EndGetClasses(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClassesCompleted(object state) {
            if ((this.GetClassesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClassesCompleted(this, new GetClassesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClassesAsync() {
            this.GetClassesAsync(null);
        }
        
        public void GetClassesAsync(object userState) {
            if ((this.onBeginGetClassesDelegate == null)) {
                this.onBeginGetClassesDelegate = new BeginOperationDelegate(this.OnBeginGetClasses);
            }
            if ((this.onEndGetClassesDelegate == null)) {
                this.onEndGetClassesDelegate = new EndOperationDelegate(this.OnEndGetClasses);
            }
            if ((this.onGetClassesCompletedDelegate == null)) {
                this.onGetClassesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClassesCompleted);
            }
            base.InvokeAsync(this.onBeginGetClassesDelegate, null, this.onEndGetClassesDelegate, this.onGetClassesCompletedDelegate, userState);
        }
        
        public bool InsertClass(SMSModule.Webservice.Class theClass) {
            return base.Channel.InsertClass(theClass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInsertClass(SMSModule.Webservice.Class theClass, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertClass(theClass, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndInsertClass(System.IAsyncResult result) {
            return base.Channel.EndInsertClass(result);
        }
        
        private System.IAsyncResult OnBeginInsertClass(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SMSModule.Webservice.Class theClass = ((SMSModule.Webservice.Class)(inValues[0]));
            return this.BeginInsertClass(theClass, callback, asyncState);
        }
        
        private object[] OnEndInsertClass(System.IAsyncResult result) {
            bool retVal = this.EndInsertClass(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertClassCompleted(object state) {
            if ((this.InsertClassCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertClassCompleted(this, new InsertClassCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertClassAsync(SMSModule.Webservice.Class theClass) {
            this.InsertClassAsync(theClass, null);
        }
        
        public void InsertClassAsync(SMSModule.Webservice.Class theClass, object userState) {
            if ((this.onBeginInsertClassDelegate == null)) {
                this.onBeginInsertClassDelegate = new BeginOperationDelegate(this.OnBeginInsertClass);
            }
            if ((this.onEndInsertClassDelegate == null)) {
                this.onEndInsertClassDelegate = new EndOperationDelegate(this.OnEndInsertClass);
            }
            if ((this.onInsertClassCompletedDelegate == null)) {
                this.onInsertClassCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertClassCompleted);
            }
            base.InvokeAsync(this.onBeginInsertClassDelegate, new object[] {
                        theClass}, this.onEndInsertClassDelegate, this.onInsertClassCompletedDelegate, userState);
        }
    }
}
